### ISSUE TITLE
quit error

### ISSUE THREAD

**Issue by BryanZhu-Us** [lordloki/EasyOnline#2]
when client quit:

[2022-06-02 17:48:51.482771]: Connected to server!
Error: Python(empty), Python script error
Traceback (most recent call last):
  File "~/Multiplayer/client.blend/EO_network.py", line 419, in process_TCP
  File "~/Multiplayer/client.blend/EO_network.py", line 307, in _shutdown
OSError: [Errno 57] Socket is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/Multiplayer/client.blend/EO_client.py", line 35, in main
  File "~/Multiplayer/client.blend/EO_network.py", line 318, in main
  File "~/Multiplayer/client.blend/EO_network.py", line 315, in recv
  File "~/Multiplayer/client.blend/EO_network.py", line 430, in process_TCP
NameError: name 'e' is not defined
Blender Game Engine Finished

and server got same erro:

[2022-06-02 17:48:53.118134]: A Client connected! - ('127.0.0.1', 55134)
Error: Python(empty), Python script error
Traceback (most recent call last):
  File "~/Multiplayer/server.blend/EO_network.py", line 419, in process_TCP
  File "~/Multiplayer/server.blend/EO_network.py", line 354, in _shutdown
OSError: [Errno 57] Socket is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/Multiplayer/server.blend/EO_server.py", line 25, in main
  File "~/Multiplayer/server.blend/EO_network.py", line 242, in main
  File "~/Multiplayer/server.blend/EO_network.py", line 185, in recv
  File "~/Multiplayer/server.blend/EO_network.py", line 387, in recv
  File "~/Multiplayer/server.blend/EO_network.py", line 430, in process_TCP
NameError: name 'e' is not defined

**Comment by BryanZhu-Us** [comment]
i found it worked fine in bpg3.0,errors in 3.3

**Comment by lordloki** [comment]
I open again to check in upbge 0.33
